"""Installed compatibility module forwarding to the current v2 scheduler."""

from factory_mt_da_scheduler_v2 import (
    Candidate,
    InfeasibleScheduleError,
    Instance,
    InstanceValidationError,
    Microturbine,
    SchedulerConfig,
    SchedulingError,
    SchedulingResult,
    SolveFailedError,
    SolverSettings,
    SolverUnavailableError,
    VerificationError,
    __version__,
    build_candidates,
    build_model,
    extract_result,
    hhmm,
    main,
    make_benchmark_instance,
    mt_fuel_cost_by_hour,
    optimize_day_ahead,
    plot_schedule,
    solve_model,
    tou_price_vectors,
    verify,
)

__all__ = [
    "Candidate",
    "InfeasibleScheduleError",
    "Instance",
    "InstanceValidationError",
    "Microturbine",
    "SchedulerConfig",
    "SchedulingError",
    "SchedulingResult",
    "SolveFailedError",
    "SolverSettings",
    "SolverUnavailableError",
    "VerificationError",
    "__version__",
    "build_candidates",
    "build_model",
    "extract_result",
    "hhmm",
    "main",
    "make_benchmark_instance",
    "mt_fuel_cost_by_hour",
    "optimize_day_ahead",
    "plot_schedule",
    "solve_model",
    "tou_price_vectors",
    "verify",
]

if __name__ == "__main__":
    raise SystemExit(main())