"""Modular three-stage industrial factory scheduling package."""

from ._internal import __version__
from .config import RunConfig
from .day_ahead import (
    BESS,
    Candidate,
    InfeasibleScheduleError,
    Instance,
    InstanceValidationError,
    Microturbine,
    SchedulerConfig,
    SchedulingError,
    SchedulingResult,
    SolveFailedError,
    SolverSettings,
    SolverUnavailableError,
    VerificationError,
    build_candidates,
    build_model,
    make_benchmark_instance,
    optimize_day_ahead,
    tou_price_vectors,
)
from .intraday import (
    IntradayMarket,
    IntradayResult,
    ScenarioSet,
    build_intraday_model,
    optimize_intraday,
    value_of_stochastic_solution,
)
from .realtime import (
    BalancingMarket,
    RealTimeResult,
    RealTimeSet,
    build_realtime_model,
    optimize_realtime,
    selftest,
    value_of_rt_modelling,
)

__all__ = [
    "BESS",
    "BalancingMarket",
    "Candidate",
    "InfeasibleScheduleError",
    "Instance",
    "InstanceValidationError",
    "IntradayMarket",
    "IntradayResult",
    "Microturbine",
    "RealTimeResult",
    "RealTimeSet",
    "RunConfig",
    "ScenarioSet",
    "SchedulerConfig",
    "SchedulingError",
    "SchedulingResult",
    "SolveFailedError",
    "SolverSettings",
    "SolverUnavailableError",
    "VerificationError",
    "__version__",
    "build_candidates",
    "build_intraday_model",
    "build_model",
    "build_realtime_model",
    "make_benchmark_instance",
    "optimize_day_ahead",
    "optimize_intraday",
    "optimize_realtime",
    "selftest",
    "tou_price_vectors",
    "value_of_rt_modelling",
    "value_of_stochastic_solution",
]